-- Starter quote templates generated from the product catalog (Aug 2026).
-- Numbers were read from src/data/* at generation time; reprices are edited
-- in the admin template editor afterward. Safe to re-run: replaces by name
-- (which also discards edits made in the admin, and renumbers template ids).
--
-- Every plan template prices BOTH billing options — "Investment — month to
-- month" and "Investment — prepay the year" — and every price line carries a
-- billing cadence (once/monthly/yearly) so quotes never add a setup fee and a
-- monthly plan into one number. Delete the option the customer isn't taking,
-- or leave both and let them choose. Regenerate with:
--   node scripts/gen-quote-template-seed.mjs
DELETE FROM quote_templates WHERE name = 'Get Found — starter website';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Get Found — starter website', 'website-basic', '[{"id":"s-7","title":"What''s included","items":[{"id":"i-1","type":"bullet","text":"A custom-designed 1–3 page website"},{"id":"i-2","type":"bullet","text":"Logo design included"},{"id":"i-3","type":"bullet","text":"Hosting, SSL, and speed handled — nothing extra to buy"},{"id":"i-4","type":"bullet","text":"Set up to rank on Google & Maps when locals search for you"},{"id":"i-5","type":"bullet","text":"Remi AI, your AI agent, answering customer questions 24/7"},{"id":"i-6","type":"bullet","text":"A contact form that reaches you the moment someone fills it"}]},{"id":"s-11","title":"Investment — month to month","items":[{"id":"i-8","type":"subtotal","label":"One-time setup (design & build)","amount":595,"billing":"once"},{"id":"i-9","type":"subtotal","label":"Monthly plan","amount":95,"billing":"monthly"},{"id":"i-10","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y1","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y2","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":950,"billing":"yearly"},{"id":"i-y3","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-15","title":"Project details","items":[{"id":"i-12","type":"fillable","label":"Business name","value":""},{"id":"i-13","type":"fillable","label":"Website domain","value":""},{"id":"i-14","type":"fillable","label":"Target start date","value":""}]}]', 1, 1);
DELETE FROM quote_templates WHERE name = 'Get Booked — website that books appointments';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Get Booked — website that books appointments', 'website-plus', '[{"id":"s-20","title":"What''s included","items":[{"id":"i-16","type":"bullet","text":"Everything in Get Found, on a full multi-page website"},{"id":"i-17","type":"bullet","text":"Remi AI books the job straight into your calendar, not just answers"},{"id":"i-18","type":"bullet","text":"Local SEO and AI-search optimization, kept fresh every month"},{"id":"i-19","type":"bullet","text":"Every lead captured into your admin so nothing slips through"}]},{"id":"s-24","title":"Investment — month to month","items":[{"id":"i-21","type":"subtotal","label":"One-time setup (design & build)","amount":895,"billing":"once"},{"id":"i-22","type":"subtotal","label":"Monthly plan","amount":245,"billing":"monthly"},{"id":"i-23","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y4","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y5","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":2450,"billing":"yearly"},{"id":"i-y6","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-28","title":"Project details","items":[{"id":"i-25","type":"fillable","label":"Business name","value":""},{"id":"i-26","type":"fillable","label":"Website domain","value":""},{"id":"i-27","type":"fillable","label":"Target start date","value":""}]}]', 1, 2);
DELETE FROM quote_templates WHERE name = 'Get Growing — self-optimizing website that sells';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Get Growing — self-optimizing website that sells', 'website-smart', '[{"id":"s-33","title":"What''s included","items":[{"id":"i-29","type":"bullet","text":"Everything in Get Booked"},{"id":"i-30","type":"bullet","text":"Full self-optimization — content written, A/B tested, and tuned continuously"},{"id":"i-31","type":"bullet","text":"Remi AI sells: steers customers to the right service and asks for the job"},{"id":"i-32","type":"bullet","text":"Immersive 360° galleries, built to get picked by AI search"}]},{"id":"s-37","title":"Investment — month to month","items":[{"id":"i-34","type":"subtotal","label":"One-time setup (design & build)","amount":1195,"billing":"once"},{"id":"i-35","type":"subtotal","label":"Monthly plan","amount":545,"billing":"monthly"},{"id":"i-36","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y7","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y8","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":5450,"billing":"yearly"},{"id":"i-y9","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-41","title":"Project details","items":[{"id":"i-38","type":"fillable","label":"Business name","value":""},{"id":"i-39","type":"fillable","label":"Website domain","value":""},{"id":"i-40","type":"fillable","label":"Target start date","value":""}]}]', 1, 3);
DELETE FROM quote_templates WHERE name = 'Get Ahead — website + managed ads bundle';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Get Ahead — website + managed ads bundle', 'get-ahead', '[{"id":"s-47","title":"What''s included","items":[{"id":"i-42","type":"bullet","text":"Everything in Get Growing"},{"id":"i-43","type":"bullet","text":"Your ads run and managed on two networks (Google + social, or two social)"},{"id":"i-44","type":"bullet","text":"Landing pages built for each campaign"},{"id":"i-45","type":"bullet","text":"You fund ad spend directly with the platform — never marked up"},{"id":"i-46","type":"bullet","text":"A monthly working session with Manny on the numbers and next moves"}]},{"id":"s-51","title":"Investment — month to month","items":[{"id":"i-48","type":"subtotal","label":"One-time setup (design & build)","amount":1195,"billing":"once"},{"id":"i-49","type":"subtotal","label":"Monthly plan","amount":895,"billing":"monthly"},{"id":"i-50","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y10","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y11","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":8950,"billing":"yearly"},{"id":"i-y12","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-55","title":"Project details","items":[{"id":"i-52","type":"fillable","label":"Business name","value":""},{"id":"i-53","type":"fillable","label":"Website domain","value":""},{"id":"i-54","type":"fillable","label":"Target start date","value":""}]}]', 1, 4);
DELETE FROM quote_templates WHERE name = 'Online Store — Sell Online (Shopify)';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Online Store — Sell Online (Shopify)', 'ecommerce', '[{"id":"s-60","title":"What''s included","items":[{"id":"i-56","type":"bullet","text":"A real Shopify store, set up right: theme, payments, shipping, taxes"},{"id":"i-57","type":"bullet","text":"The Shopify account is opened in your name and billed by Shopify — the store is always yours"},{"id":"i-58","type":"bullet","text":"Remi AI answers shoppers 24/7 from day one"},{"id":"i-59","type":"note","text":"Shopify’s own subscription is billed by Shopify and is not included (Basic at this tier)."}]},{"id":"s-65","title":"Investment — month to month","items":[{"id":"i-61","type":"subtotal","label":"One-time setup (store build)","amount":745,"billing":"once"},{"id":"i-62","type":"subtotal","label":"Monthly plan — Sell Online","amount":150,"billing":"monthly"},{"id":"i-63","type":"note","text":"Higher tiers: Sell More $1,045 setup + $325/mo · Sell Smarter $1,345 + $650/mo · Sell Everywhere $1,645 + $1,095/mo."},{"id":"i-64","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y13","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y14","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":1500,"billing":"yearly"},{"id":"i-y15","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-69","title":"Project details","items":[{"id":"i-66","type":"fillable","label":"Business name","value":""},{"id":"i-67","type":"fillable","label":"Website domain","value":""},{"id":"i-68","type":"fillable","label":"Target start date","value":""}]}]', 1, 5);
DELETE FROM quote_templates WHERE name = 'One-Page Website — Remi AI Lite with a page included';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('One-Page Website — Remi AI Lite with a page included', 'ai-website', '[{"id":"s-73","title":"What''s included","items":[{"id":"i-70","type":"bullet","text":"A one-page website, designed and built for your business"},{"id":"i-71","type":"bullet","text":"Remi AI Lite: answers customer questions 24/7 and captures every lead"},{"id":"i-72","type":"bullet","text":"Hosting, SSL, and speed handled"}]},{"id":"s-77","title":"Investment — month to month","items":[{"id":"i-74","type":"subtotal","label":"One-time setup","amount":195,"billing":"once"},{"id":"i-75","type":"subtotal","label":"Monthly (Remi AI Lite subscription)","amount":40,"billing":"monthly"},{"id":"i-76","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y16","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y17","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":400,"billing":"yearly"},{"id":"i-y18","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-81","title":"Project details","items":[{"id":"i-78","type":"fillable","label":"Business name","value":""},{"id":"i-79","type":"fillable","label":"Website domain","value":""},{"id":"i-80","type":"fillable","label":"Target start date","value":""}]}]', 1, 6);
DELETE FROM quote_templates WHERE name = 'Remi AI — chat agent for your website';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Remi AI — chat agent for your website', 'remi-ai', '[{"id":"s-83","title":"Plan","items":[{"id":"i-82","type":"choice","label":"Remi AI plan","value":"","options":["Remi AI Lite — $40/mo (answers & captures leads)","Remi AI — $75/mo (adds the full customization admin)","Remi AI Pro — $145/mo (adds booking into your calendar)"]}]},{"id":"s-88","title":"What''s included","items":[{"id":"i-84","type":"bullet","text":"Brand Brain: scans your site, learns your business — you approve every fact it keeps"},{"id":"i-85","type":"bullet","text":"Leads inbox: every captured lead in the admin, also emailed to you"},{"id":"i-86","type":"bullet","text":"Embeds on any website with one snippet"},{"id":"i-87","type":"bullet","text":"Manny configures at setup and trains you — then the admin is yours"}]},{"id":"s-91","title":"Investment — month to month","items":[{"id":"i-89","type":"subtotal","label":"One-time setup","amount":195,"billing":"once"},{"id":"i-y19","type":"subtotal","label":"Monthly plan — Remi AI","amount":75,"billing":"monthly"},{"id":"i-90","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y20","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y21","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":750,"billing":"yearly"},{"id":"i-y22","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-95","title":"Project details","items":[{"id":"i-92","type":"fillable","label":"Business name","value":""},{"id":"i-93","type":"fillable","label":"Website domain","value":""},{"id":"i-94","type":"fillable","label":"Target start date","value":""}]}]', 1, 7);
DELETE FROM quote_templates WHERE name = 'AI Agents Team — Manny AI, priced per workflow';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('AI Agents Team — Manny AI, priced per workflow', 'ai-team', '[{"id":"s-97","title":"Plan","items":[{"id":"i-96","type":"choice","label":"Manny AI tier","value":"","options":["One Workflow — $245/mo","Growth (up to three workflows) — $595/mo","Agency (unlimited within normal use) — $1,195/mo"]}]},{"id":"s-102","title":"What''s included","items":[{"id":"i-98","type":"bullet","text":"Priced per workflow (one defined business process) — as many agents as it needs"},{"id":"i-99","type":"bullet","text":"Brand Brain built for your business; the first workflow trained with you"},{"id":"i-100","type":"bullet","text":"Normal AI usage included; third-party seats pass through at cost"},{"id":"i-101","type":"bullet","text":"Workflows with real integrations are scoped on the free diagnostic first"}]},{"id":"s-105","title":"Investment — month to month","items":[{"id":"i-103","type":"subtotal","label":"One-time setup","amount":195,"billing":"once"},{"id":"i-y23","type":"subtotal","label":"Monthly plan — One Workflow","amount":245,"billing":"monthly"},{"id":"i-104","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff; after that the setup fee is non-refundable."}]},{"id":"s-y24","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y25","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":2450,"billing":"yearly"},{"id":"i-y26","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10 and waives the one-time setup fee in full. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-109","title":"Project details","items":[{"id":"i-106","type":"fillable","label":"Business name","value":""},{"id":"i-107","type":"fillable","label":"Website domain","value":""},{"id":"i-108","type":"fillable","label":"Target start date","value":""}]}]', 1, 8);
DELETE FROM quote_templates WHERE name = 'On the Map — Local SEO + 360° media';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('On the Map — Local SEO + 360° media', 'seo-on-the-map', '[{"id":"s-113","title":"What''s included","items":[{"id":"i-110","type":"bullet","text":"Local SEO foundation: Google Business Profile tuned and kept active"},{"id":"i-111","type":"bullet","text":"360° photography for your profile and listings"},{"id":"i-112","type":"bullet","text":"Monthly reporting on where you rank and what changed"}]},{"id":"s-116","title":"Investment — month to month","items":[{"id":"i-114","type":"subtotal","label":"Monthly package","amount":245,"billing":"monthly"},{"id":"i-115","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff."}]},{"id":"s-y27","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y28","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":2450,"billing":"yearly"},{"id":"i-y29","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10, two months free. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-120","title":"Project details","items":[{"id":"i-117","type":"fillable","label":"Business name","value":""},{"id":"i-118","type":"fillable","label":"Website domain","value":""},{"id":"i-119","type":"fillable","label":"Target start date","value":""}]}]', 1, 9);
DELETE FROM quote_templates WHERE name = 'Own the Map — Local SEO + virtual tour';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Own the Map — Local SEO + virtual tour', 'seo-own-the-map', '[{"id":"s-124","title":"What''s included","items":[{"id":"i-121","type":"bullet","text":"Everything in On the Map"},{"id":"i-122","type":"bullet","text":"A full virtual tour of your business, published where customers look"},{"id":"i-123","type":"bullet","text":"Deeper citation and review work across the map pack"}]},{"id":"s-127","title":"Investment — month to month","items":[{"id":"i-125","type":"subtotal","label":"Monthly package","amount":495,"billing":"monthly"},{"id":"i-126","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff."}]},{"id":"s-y30","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y31","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":4950,"billing":"yearly"},{"id":"i-y32","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10, two months free. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-131","title":"Project details","items":[{"id":"i-128","type":"fillable","label":"Business name","value":""},{"id":"i-129","type":"fillable","label":"Website domain","value":""},{"id":"i-130","type":"fillable","label":"Target start date","value":""}]}]', 1, 10);
DELETE FROM quote_templates WHERE name = 'Own the Market — full SEO program';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Own the Market — full SEO program', 'seo-own-the-market', '[{"id":"s-135","title":"What''s included","items":[{"id":"i-132","type":"bullet","text":"The full local SEO program: content, citations, reviews, and technical work"},{"id":"i-133","type":"bullet","text":"Everything in Own the Map, run as an ongoing campaign"},{"id":"i-134","type":"bullet","text":"Monthly strategy review of rankings, traffic, and leads"}]},{"id":"s-138","title":"Investment — month to month","items":[{"id":"i-136","type":"subtotal","label":"Monthly package","amount":995,"billing":"monthly"},{"id":"i-137","type":"note","text":"Billed monthly, starting at kickoff. No minimum term and no exit charge, cancel anytime. Full refund within 5 business days of kickoff."}]},{"id":"s-y33","title":"Investment — prepay the year (two months free)","items":[{"id":"i-y34","type":"subtotal","label":"Year prepaid (12 months for the price of 10)","amount":9950,"billing":"yearly"},{"id":"i-y35","type":"note","text":"Two ways to pay for the same service, pick one. Prepaying covers 12 months for the price of 10, two months free. Full refund within 5 business days of kickoff; after that, prepaid years are non-refundable."}]},{"id":"s-142","title":"Project details","items":[{"id":"i-139","type":"fillable","label":"Business name","value":""},{"id":"i-140","type":"fillable","label":"Website domain","value":""},{"id":"i-141","type":"fillable","label":"Target start date","value":""}]}]', 1, 11);
DELETE FROM quote_templates WHERE name = 'Scripts & Tools — small business app';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Scripts & Tools — small business app', 'app-scripts', '[{"id":"s-146","title":"Scope","items":[{"id":"i-143","type":"bullet","text":"A focused script or tool that automates one job in your business"},{"id":"i-144","type":"bullet","text":"Runs standalone — no accounts to connect"},{"id":"i-145","type":"fillable","label":"What it should do","value":""}]},{"id":"s-149","title":"Investment","items":[{"id":"i-147","type":"subtotal","label":"Build (starting at)","amount":300,"billing":"once"},{"id":"i-148","type":"note","text":"Flat $75/hr — final quote after scoping the exact job."}]},{"id":"s-153","title":"Project details","items":[{"id":"i-150","type":"fillable","label":"Business name","value":""},{"id":"i-151","type":"fillable","label":"Website domain","value":""},{"id":"i-152","type":"fillable","label":"Target start date","value":""}]}]', 1, 12);
DELETE FROM quote_templates WHERE name = 'Connected Apps — integrations & MCP';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Connected Apps — integrations & MCP', 'app-integration', '[{"id":"s-157","title":"Scope","items":[{"id":"i-154","type":"bullet","text":"Connects the systems you already use so data moves itself"},{"id":"i-155","type":"bullet","text":"Includes MCP setup where an AI agent should drive the tool"},{"id":"i-156","type":"fillable","label":"Systems to connect","value":""}]},{"id":"s-160","title":"Investment","items":[{"id":"i-158","type":"subtotal","label":"Build (starting at)","amount":600,"billing":"once"},{"id":"i-159","type":"note","text":"Flat $75/hr — final quote after scoping the exact job."}]},{"id":"s-164","title":"Project details","items":[{"id":"i-161","type":"fillable","label":"Business name","value":""},{"id":"i-162","type":"fillable","label":"Website domain","value":""},{"id":"i-163","type":"fillable","label":"Target start date","value":""}]}]', 1, 13);
DELETE FROM quote_templates WHERE name = 'Business App — custom build';
INSERT INTO quote_templates (name, project_type, sections, is_default, sort_order)
VALUES ('Business App — custom build', 'custom-app', '[{"id":"s-168","title":"Scope","items":[{"id":"i-165","type":"bullet","text":"A custom application built around how your business runs"},{"id":"i-166","type":"bullet","text":"Scoped together first — you approve the plan before the build starts"},{"id":"i-167","type":"fillable","label":"The problem it solves","value":""}]},{"id":"s-171","title":"Investment","items":[{"id":"i-169","type":"subtotal","label":"Build (starting at)","amount":2500,"billing":"once"},{"id":"i-170","type":"note","text":"Flat $75/hr — final quote after scoping the exact job."}]},{"id":"s-175","title":"Project details","items":[{"id":"i-172","type":"fillable","label":"Business name","value":""},{"id":"i-173","type":"fillable","label":"Website domain","value":""},{"id":"i-174","type":"fillable","label":"Target start date","value":""}]}]', 1, 14);
